# Nome do processo
name: Update automático

on:
  schedule:
    # cron é o "intervalo" de execução
    # nesse caso, ele irá rodar diariamente às 6h.
    - cron: '0 6 * * *'

# Aqui vem os passos que a ação segue
jobs:
  build:
    # Inicia uma máquina virtual ubuntu
    runs-on: ubuntu-latest

    # Checa o código atual do repositório
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Instala o Python na versão 3.10
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instala dependencias
      run: |
        python -m pip install --upgrade pip

    # o nome do arquivo python
    - name: Roda o arquivo
      run: |
        python app.py
        cat README.md

    # E no final commita e faz um push caso haja alguma diferença
    # comparada ao código atual do repositório
    - name: Commit e push
      run: |-
        git diff
        git config --global user.email "bot-readme@example.com"
        git config --global user.name "bot automático"
        git add -A
        git commit -m "doc: Descrição atualizada!"
        git push
